version: '3.2' # in 3 , there is volumes issue ...
services:
  mongo1:
    image: "mongo"
    ports:
      - "10000:27017"
    volumes: # container -> local로 mount할 수 있습니다.
      - type: bind
        source: ./data/db # local 경로
        target: /data/db  # container 내부에서의 경로
    networks:
      - mongo-networks
    command: mongod --replSet replication
  mongo2:
    image: "mongo"
    ports:
      - "10001:27017"
    volumes: # container -> local로 mount할 수 있습니다.
      - type: bind
        source: ./data2/db # local 경로
        target: /data2/db  # container 내부에서의 경로
    networks:
      - mongo-networks
    command: mongod --replSet replication
    depends_on:
      - mongo1
  mongo3:
    image: "mongo"
    ports:
      - "10002:27017"
    volumes: # container -> local로 mount할 수 있습니다.
      - type: bind
        source: ./data3/db # local 경로
        target: /data3/db  # container 내부에서의 경로
    networks:
      - mongo-networks
    command: mongod --replSet replication
    depends_on:
      - mongo2
  mongosetup:
    image: "mongo-setup"
    depends_on:
      - mongo1
    networks:
      - mongo-networks

networks:
  mongo-networks:
    driver: bridge